name: SonarQube Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # 1. Haal de code op
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Voer de SonarQube analyse uit
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=sonar-booomtag-test
            -Dsonar.projectName="CI-CD-Booomtag"
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://3.248.191.80:9000"

      # 3. Quality Gate check
      #    Hiermee faalt de pipeline als de codekwaliteit onvoldoende is.
      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://3.248.191.80:9000"
